export function sendGridTemplate() {

    const templateId = {

        REGISTER_TEMPLATE: '',
        FORGOT_PASSWORD_TEMPLATE: '',
        TEACHER_PROFILE_APPROVED: '',
        TEACHER_PROFILE_REJECTED: '',

        //FREELANCE RECORDED SESSIONS
        FREELANCE_SESSION_APPROVED: '',
        FREELANCE_SESSION_REJECTED: '',
        FREELANCE_RECORD_SESSION_REVIEWED: '',
        FREELANCE_RECORD_SESSION_REVIEW_CHALLENGED: '',
        FREELANCE_RECORD_SESSION_FAVORITES: '',
        FREELANCE_RECORD_SESSION_PURCHASED: '',

        //FREELANCE LIVE SESSIONS
        FREELANCE_LIVE_SESSION_CREATE_TEMPLATE: '',
        FREELANCE_LIVE_SESSION_UPDATE_TEMPLATE: '',
        FREELANCE_LIVE_SESSION_REVIEWED: '',
        FREELANCE_LIVE_SESSION_REVIEW_CHALLENGED: '',
        FREELANCE_LIVE_SESSION_FAVORITES: '',
        FREELANCE_LIVE_SESSION_PURCHASED: '',
        FREELANCE_LIVE_SESSION_START_REMINDER: '',

        //PROFILE BOOKING
        FREELANCE_TEACHER_PROFILE_BOOKING: '',

        //SCHOOL




    }

}
